🚧Fix nuget package check issue
KinsonDigital/CICD pull request #130
Opened 2022-12-14 14:04 UTC by CalvinWilkinson

<h1 style="font-weight:bold" align="center">Preview Feature Pull Request</h1>
<h2 style="font-weight:bold" align="center">📋Review Checklist📋</h2>

- [ ] The **_head(source)_** branch for this pull request is a **_preview feature_** branch, with the correct naming syntax, in the following example:
  - A **_head(source)_** branch is the branch being merged into a target branch.
    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/feature/<issue-num>-<description>
      Example: preview/feature/123-my-preview-feature
      ```
    </details>

- [ ] The **_head(source)_** branch for this pull request is created from a **_preview release_** branch, with the correct naming syntax, in the following example:
  <details closed><summary>Example</summary>

    ``` xml
    Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
    Example: preview/v1.2.3-preview.4
    ```
  </details>

- [ ] The **_base(target)_** branch for this pull request is a **_preview release_** branch, with the correct naming syntax, in the following example:
  - A **_base(target)_** branch is the branch that the **_head(source)_** branch is merging into.

    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
      Example: preview/v1.2.3-preview.4
      ```
    </details>

💡For more information on branching, refer to the project's [branching documentation](../../Documentation/Branching.md).

- [ ] Associated issue exists and is linked to this pull request.
  - One issue per pull request.

- [ ] Pull request title matches the title of the associated issue.

- [ ] A `preview` label has been added to the pull request.

- [ ] The labels attached to this PR match the labels attached to the associated issue.

- [ ] Project assigned matches the project of the associated issue.

- [ ] Milestone assigned matches the milestone of the associated issue.

- [ ] My code follows the coding style of this project.
  - The style is enforced by the **_.editorconfig_** files in the project and displayed as warnings.  If there is an edge case, reach out, and let's discuss it.

- [ ] I have manually tested my code changes to the best of my ability.

- [ ] All tests passed locally.
  - This is required because unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
  - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
  - Status checks run for this pull request when merging into the **_preview/v\*.\*.\*-preview.\*_** branch.  These status checks run every time a change is pushed to the pull request.  These checks validate version syntax, tagging, builds, unit tests, and more.

2022-12-15 14:24 UTC, KinsonDigitalAdmin requested changes

2022-12-15 14:24 UTC, KinsonDigitalAdmin commented on CICD.sln.DotSettings
> +	<s:Boolean x:Key="/Default/UserDictionary/Words/=VVVVV/@EntryIndexedValue">True</s:Boolean></wpf:ResourceDictionary>
Add a single empty line to the end of the file.

2022-12-15 14:24 UTC, KinsonDigitalAdmin commented on CICD/ExtensionMethods.cs
> +    public static string ToCrossPlatPath(this string value)
Add code docs

2022-12-15 14:24 UTC, KinsonDigitalAdmin commented on CICD/ExtensionMethods.cs
> +    public static string[] ToCrossPlatPaths(this IEnumerable<string>? paths)
Add code docs

2022-12-15 14:36 UTC, KinsonDigitalAdmin submitted a review, later dismissed

2022-12-16 15:49 UTC, kselena requested changes

2022-12-16 15:49 UTC, kselena commented on CICD/ExtensionMethods.cs
> +    ///     This simply takes all windows specific directory separator characters and
Refactor to remove simply
```suggestion
    ///     This takes all windows specific directory separator characters and
```

2022-12-16 15:49 UTC, kselena commented on CICD/Services/Interfaces/IFindDirService.cs
>      /// <param name="dirNameToFind">The name to the directory to find.</param>
Grammar
```suggestion
    /// <param name="dirNameToFind">The name of the directory to find.</param>
```

2022-12-16 16:01 UTC, kselena commented on CICD/Services/Interfaces/IFindDirService.cs
>      /// <param name="dirNameToFind">The name to the directory to find.</param>
@CalvinWilkinson I don't see that this has been changed.

2022-12-16 16:03 UTC, kselena approved these changes

2022-12-16 16:05 UTC, KinsonDigitalAdmin approved these changes

2022-12-16 16:57 UTC, merged