🚧Requirements added to hotfix pr status check target
KinsonDigital/CICD pull request #98
Opened 2022-10-13 11:06 UTC by CalvinWilkinson

<h1 style="font-weight:bold" align="center">Preview Feature Pull Request</h1>
<h2 style="font-weight:bold" align="center">✅Code Review Checklist✅</h2>

- [ ] The **_head(source)_** branch for this pull request is a **_preview feature_** branch, with the correct naming syntax, in the following example:
  - A **_head(source)_** branch is the branch being merged into a target branch.
    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/feature/<issue-num>-<description>
      Example: preview/feature/123-my-preview-feature
      ```
    </details>

- [ ] The **_head(source)_** branch for this pull request is created from a **_preview release_** branch, with the correct naming syntax, in the following example:
  <details closed><summary>Example</summary>

    ``` xml
    Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
    Example: preview/v1.2.3-preview.4
    ```
  </details>

- [ ] The **_base(target)_** branch for this pull request is a **_preview release_** branch, with the correct naming syntax, in the following example:
  - A **_base(target)_** branch is the branch that the **_head(source)_** branch is merging into.

    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
      Example: preview/v1.2.3-preview.4
      ```
    </details>

💡For more information on branching, refer to the project's [branching documentation](../../Documentation/Branching.md).

- [ ] Associated issue exists and is linked to this pull request.
  - One issue per pull request.

- [ ] Pull request title matches the title of the associated issue.

- [ ] A `preview` label has been added to the pull request.

- [ ] The labels attached to this PR match the labels attached to the associated issue.

- [ ] Project assigned matches the project of the associated issue.

- [ ] Milestone assigned matches the milestone of the associated issue.

- [ ] My code follows the coding style of this project.
  - The style is enforced by the **_.editorconfig_** files in the project and displayed as warnings.  If there is an edge case, reach out and let's discuss it.

- [ ] I have manually tested my code changes to the best of my ability.

- [ ] All tests passed locally.
  - This is required because unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
  - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
  - Status checks run for this pull request when merging into the **_preview/v\*.\*.\*-preview.\*_** branch.  These status checks run every time a change is pushed to the pull request.  These checks validate version syntax, tagging, builds, unit tests, and more.

2022-10-13 14:52 UTC, KinsonDigitalAdmin requested changes

2022-10-13 14:52 UTC, KinsonDigitalAdmin commented on CICD/CICD.Requirements.cs
> +    /// Returns a value indicating if the pull request contains a label that matches the given <paramref name="labels"/>.
Refactor to below:

```suggestion
    /// Returns a value indicating whether or not the pull request contains a label that matches the given <paramref name="labels"/>.
```

2022-10-13 14:52 UTC, KinsonDigitalAdmin commented on CICD/CICD.StatusChecks.cs
> +            () => ThatTheReleaseMilestoneOnlyContainsSingleReleaseItem(ReleaseType.Preview, ItemType.PullRequest),
Remove these requirement methods

2022-10-13 14:52 UTC, KinsonDigitalAdmin commented on CICD/CICD.StatusChecks.cs
> +            () => ThatTheReleaseMilestoneOnlyContainsSingleReleaseItem(ReleaseType.Production, ItemType.PullRequest),
Remove these requirement methods

2022-10-13 14:52 UTC, KinsonDigitalAdmin commented on CICD/ExtensionMethods.cs
> +    /// Returns a value indicating if a GitHub issue is a release to do issue.
Refactor code comments

```suggestion
    /// Returns a value indicating whether or not a GitHub issue is a release to do issue.
```

2022-10-13 14:52 UTC, KinsonDigitalAdmin commented on CICD/ExtensionMethods.cs
> +    /// Returns a value indicating if a GitHub issue is a release pull request.
Refactor code comments

```suggestion
    /// Returns a value indicating whether or not a GitHub issue is a release pull request.
```

2022-10-13 14:56 UTC, KinsonDigitalAdmin approved these changes

2022-10-14 09:21 UTC, kselena requested changes

2022-10-14 09:21 UTC, kselena commented on CICD/CICD.Requirements.cs
> +    /// <param name="releaseType">The type of release of the item.</param>
Wordy
```suggestion
    /// <param name="releaseType">The type of item release.</param>
```

2022-10-14 09:21 UTC, kselena commented on CICD/CICD.Requirements.cs
> +    /// <returns><c>true</c> if only single item exists in the milestone.</returns>
Grammar
```suggestion
    /// <returns><c>true</c> if only a single item exists in the milestone.</returns>
```

2022-10-14 09:21 UTC, kselena commented on CICD/ExtensionMethods.cs
> +    /// <returns><c>true</c> if a standard issue.</returns>
Refactor to below, throughout the codebase.
```suggestion
    /// <returns><c>true</c> if the issue is standard.</returns>
```

2022-10-14 09:21 UTC, kselena commented on CICD/ExtensionMethods.cs
> +    /// <returns><c>true</c> if a release pull request.</returns>
Refactor to below throughout the code base
```suggestion
    /// <returns><c>true</c> if it's a release pull request.</returns>
```

2022-10-14 09:38 UTC, kselena submitted a review, later dismissed

2022-10-14 10:38 UTC, KinsonDigitalAdmin approved these changes

2022-10-14 10:38 UTC, merged